### ISSUE TITLE
Love this, but can we open up support outside of Ollama

### ISSUE THREAD

**Issue by taltoris** [Haervwe/open-webui-tools#3]
This is brilliant, but I would like to use it with VLLM or another OpenAI-style-api.

Is this already included, and I was just not able to set it up? Or is Ollama the way to go for now? If the latter, could we get some OpenAI-api compatibility in the future?

Thanks for all your work on this!

**Comment by Haervwe** [comment]
Hi thanks for trying out ! It's using the abstraction of Open-webUI so it should work with any openai compatible endpoint, I checked groq, and local and it works, maybe you are not using the correct name flag?, I don't have resources to really test it in other environments than local and free tiers, if you can we can coordinate a call and we see really where the issue lies!

**Comment by Haervwe** [comment]
well i tested it also with openrouter and they work, you need to use the model name for the provider and if you have setted it with a prepend in openwebui you should add it as this : " OpenRouter.huggingfaceh4/zephyr-7b-beta:free "
